src/pages/index.tsx

See https://github.com/yuanjian-org/app/assets/9847625/fc715e6d-5a1e-47b2-845f-95f58963b8e4 for a demo

Simplify and improve UX of the name input dialog

---

src/horizon-ui/README.md
src/horizon-ui/components/navbar/NavbarLinksAdmin.tsx
src/horizon-ui/components/sidebar/components/Links.tsx
src/horizon-ui/types/navigation.d.ts
src/routes.tsx

Move "User Profile" menu from sidebar to navbar & simplify navbar code

---

src/pages/index.tsx

See https://reactjs.org/link/warning-keys

Add keys to meeting list to fix console warning

---

src/guard.ts
src/horizon-ui/components/navbar/NavbarLinksAdmin.tsx
src/layouts/index.tsx
src/pages/callback.tsx
src/pages/login.tsx

... by moving Guard object construction outside of Guarded in index.tsx.

Remove two extra calls to authing.cn/.../public-config & minor cleanups

---

src/api/routes/user.ts
src/layouts/index.tsx
src/pages/index.tsx
src/pages/user-profile.tsx

Merge user.enter functions into user.profile to remove API calls to user.enter on every page reload.

Optimize away user.enter API call

---

src/api/auth.ts
src/api/routes/myMeetings.ts
src/api/routes/user.ts

Also changed user.profile API's semantics to only allow authenticated users to call.

Remove an extra User.findOne DB query for user.* API routes

---

src/api/auth.ts
src/api/context.ts
src/api/initApiServer.ts
src/api/tServer.ts
src/pages/api/trpc/[trpc].ts

So we can handle caching of both authingUser and user in one place.

Move getAuthingUser() from context.ts to auth.ts

---

src/api/routes/groups.ts
src/api/routes/me.ts
src/api/routes/myGroups.ts
src/layouts/index.tsx
src/pages/index.tsx
src/shared/publicModels/PublicGroup.ts
src/shared/publicModels/PublicUser.ts

- Use trpc output validation
- Use nested sequelize eager fetching

Refactor API routes

---

src/api/database/models/Group.ts
src/api/routes/myGroups.ts
src/pages/index.tsx

Display # transcripts on group lists

---

docs/UIStyle.md
package.json
src/api/database/models/Transcript.ts
src/api/routes/groups.ts
src/horizon-ui/components/navbar/NavbarLinksAdmin.tsx
src/layouts/index.tsx
src/pages/groups/[id].tsx
src/pages/index.tsx
src/pages/users.tsx
src/routes.tsx
src/shared/RBAC.ts

Add group page and supporting API

---

src/api/database/models/Summary.ts
src/api/routes/transcripts.ts
src/pages/groups/[groupId]/index.tsx
src/pages/groups/[groupId]/transcripts/[transcriptId].tsx
src/routes.tsx

Implement transcript page

---

src/api/routes/partnerships.ts
src/components/AssessmentsPanel.tsx
src/components/Autosaver.tsx
src/components/MarkdownEditor.tsx
src/pages/groups/[groupId]/transcripts/[transcriptId].tsx
src/pages/partnerships.tsx
src/pages/partnerships/[partnershipId].tsx
src/pages/partnerships/[partnershipId]/assessments.tsx
src/pages/partnerships/[partnershipId]/assessments/[assessmentId].tsx
src/shared/Partnership.ts

- Also created AutosavingMarkdownEditor

Autosave for private mentor notes

---

src/pages/profile.tsx

- fix editable by change onchange to onsubmit.
- remove save button and use editable confirm button to save the name change.

fix editable input by changing onchange to onsubmit

---

.eslintrc.json
.vscode/extensions.json

apply the import path restrictions required in README

add import restriction rules

---

src/components/Loader.tsx
src/pages/profile.tsx

- Use SimpleGrid to vertically align email and name fields
- Add a default loadingText attribute to <loader>, add loader to profile page
- Remove unused import

Some UI changes on profile.tsx

---

src/api/parseSpeakerStats.test.ts

use chai library update test file

---

src/pages/profile.tsx

Replace hardcoded width with simple grid width to fix the display issue on mobile side

fix user profile simple grid width

---

.dockerignore
Dockerfile
README.md
docker-compose.production.yml
docker-compose.yml
next.config.js
package.json

Created Docker-related configurations and instructions.
Details:
- Added a new dependency `sharp`  in `package.json` as recommended by [NextJS](https://nextjs.org/docs/messages/install-sharp).
- Forked NextJS official [`Dockerfile`](https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/next-app/prod.Dockerfile), but it is a bit outdated so made some changes based on it.
More potential optimizations:
- https://github.com/vercel/next.js/discussions/16995.

Add Docker configurations.

---

src/api/database/models/User.ts

add user paranoid model

---

src/api/routes/meetings.ts

A new condition is added to `updateOngoingMeeting()` to improve the corner case when a user creates a meeting but does not join right away. This could lead to the problem of users of the same group joining different meetings when other users of the same group create a meeting and overwrite the previously created link.
Now `updateOngoingMeeting()` will check if the meeting has been created for more than 3 minutes, and only destroy the meeting if it exists for more than 3 minutes and has no users in the meeting,

Fix Tencent Meeting Corner case

---

src/api/routes/users.ts

Remove the "me" API from users, and use session.user instead

remove trpc.users.me

---

tools/generateTestData.ts

added `{{name}}` to `yarn gen-test-data` when generating summaries for testing name mapping API later

Add handlebars to gen-test-data

---

src/api/database/db.ts
src/api/database/models/SummaryNameMap.ts
src/api/routes/transcripts.ts

Rename summaryNameMapping to summaryNameMap as instructed in PR 210

Rename Summary Name Map model

---

package.json
yarn.lock

This reverts commit ac7478da7bdb5d65c1df402c0a224f45e5940d65.

Revert "yarn upgrade next"

---

src/api/routes/assessments.ts
src/api/routes/mentorships.ts
src/api/routes/transcripts.ts
src/api/routes/users.ts
src/components/Sidebar.tsx
src/pages/users.tsx
src/shared/Role.ts
tools/migrateData.ts

Migrate role names

---

package.json
yarn.lock

[13.4.19](https://github.com/vercel/next.js/commit/d96e0258de2caf34e9322d0d32ab5748533c4465) should be the last official release before 13.5

update next to 13.4.19

---

README.md
docs/package.json.md

Add instructions for handling exclusive Windows environment errors to the README

Edit README for windows environment

---

src/pages/resources.tsx

bug fix 291 - make resource full height

---

src/components/Transcripts.tsx

Filtered transcripts with durations under 1 minute

Omit meeting transcripts

---

package.json
yarn.lock

Update axios to 1.73 to resolve Dependabot Alert

Update axios to 1.73

---

src/api/apiRouter.ts
src/api/map/routes/map.ts
src/shared/Map.ts

Added `map.ts` under `map/route` containing the skeleton of the routers. This initial implementation includes the router structure without any functions implemented.

Add map api route

---

src/components/GroupBar.tsx

Added open the meeting link in a new tab

---

src/components/ChatRoom.tsx

Right aligned dropdown with Spacer

---

src/components/ChatRoom.tsx

Added markdown link under chat editor

---

src/components/EditableWithIcon.tsx

Support multiple-lines in read mode

---

src/components/LandmarkDrawer.tsx
src/pages/map/index.tsx

Add landmark drawer

---

src/components/LandmarkDrawer.tsx

add drawer close button

---

src/components/LandmarkDrawer.tsx

add four levels for each landmark

---

src/components/ChatRoom.tsx
src/components/LandmarkDrawer.tsx
src/components/MarkdownSupport.tsx

Add history frontend

---

Dockerfile
docker-compose.yml
package.json

Fix the docker "output: standalone" error.

---

src/components/Interviews.tsx

count total interviews in interview page

---

src/pages/mentees.tsx

add source column in student file page

---

src/components/LandmarkDrawer.tsx
src/pages/map/index.tsx
src/shared/Map.ts

display landmark assessments hostory in frontend

---

src/pages/interviews.tsx

count total applicants in interview page

---

src/components/AuthPageContainer.tsx
src/components/Footer.tsx

add icp in login page

---

src/components/LandmarkDrawer.tsx

Fixed https://github.com/yuanjian-org/app/pull/394#discussion_r1796304436

simple score

---

src/api/database/models/Calibration.ts
src/api/database/models/attributesAndIncludes.ts
src/api/routes/calibrations.ts
src/components/CalibrationManagerCells.tsx
src/pages/interviews.tsx
src/shared/Calibration.ts

Add manager

---

src/components/Sidebar.tsx

Add manage menu

---

src/pages/interviews.tsx
src/pages/mentees.tsx

Fixed #383. 
Firstly sort by sources. If no source, sort by name.

sort interviews by sources then names

---

src/pages/interviews.tsx
src/pages/mentees.tsx

Revert "sort interviews by sources then names"

---

src/components/InterviewEditor.tsx
tools/migrateData.ts

change db json key name

---

src/api/routes/interviews.ts
src/pages/interviews.tsx

add getInterviewStats

---

src/components/Sidebar.tsx
src/pages/interviewerStats.tsx

frontend for stats

---

src/api/database/models/User.ts
src/api/routes/migration.ts
src/api/routes/users.ts

resolve #265
change the column type to array of varchar by following steps
1. create a new role with array type
2. copy all values from existing roles to the new role 
3. delete the old roles col
4. rename the new column to roles

change the column type for roles

---

src/api/database/models/User.test.ts
src/api/routes/users.ts
src/pages/profile.tsx
src/pages/users.tsx

add usermanger edit data

---

src/pages/interviewerStats.tsx
src/pages/profile.tsx

add toast to display successful saving message

---

src/api/routes/interviews.ts
src/pages/interviewerStats.tsx

add role in interviewStats

---

src/pages/interviews.tsx
src/pages/mentees.tsx
src/shared/strings.ts

Fixed #383.
Only sort if there is a change.

sorting interviews by sources

---

src/pages/_app.tsx
src/pages/map/index.tsx

add getStaticProps map

---

package-lock.json
src/components/Interviews.tsx

add pointOfContact to calibration page

---

src/components/InterviewEditor.tsx

add remove score feature

---

src/components/InterviewEditor.tsx

prevent readonly user from resetting score

---

src/api/sendgrid.ts
src/components/Applicant.tsx
src/components/AutosaveIndicator.tsx
src/components/ConsentModal.tsx
src/components/Navbars.tsx
src/components/UserCards.tsx
src/components/UserFilterSelector.tsx
src/pages/groups.tsx
src/pages/index.tsx
src/pages/mentors/manage.tsx
src/pages/preferences/[userId].tsx
src/pages/profiles/[userId].tsx
src/pages/users.tsx
src/shared/replaceUrlParam.ts

structuredClone is not supported by all modern browser versions

Replace all structuredClone

---

src/components/UserCards.tsx

use Flex to avoid overflow

---

src/api/routes/interviews.ts

This reverts commit 5e0422aa9abf53ecaf82e9c11c1289cafad6a7ee.

Revert "TEMPORARY: Notion mentor interview data backfill"
