yuanjian-org/app

src/api/database/sequelizeInstance.ts

Task: https://www.notion.so/yuanjian/3524bb9cffe64164bd85f6e04b1e866c
Reference: https://sequelize.org/api/v6/identifiers.html#errors
Didn't find other retry-safe errors other than ConnectionError. Also maximum of 3 times is kinda default. 
Have tested on my local machine that it do retries when I kill DB process, but didn't find a way to do exponential backoff.

Allow DB connection retry.

---

package.json
src/api/auth.ts
src/api/routes/user.ts
yarn.lock

Significantly improve loading time by avoiding repeated calls to authing.cn and db query:
> User cache miss for 'fooo@bar'. Time spent in ms:
>
> getAuthingUser():   1149
> findOrCreateUser(): 931

User caching

---

tools/syncDatabase.ts

If users really want to start over, the cleanest way is to drop db and recreate a new one.

Remove dropping db option from `yarn sync-database`

---

.eslintrc.json
.vscode/extensions.json
README.md
src/api/routes/transcripts.ts
src/pages/groups/[groupId]/transcripts/[transcriptId].tsx
src/shared/Transcript.ts

- Updated import restriction rules in `eslintrc.json` on `src/pages/api` and `*.ts` and `*.tsx` files
- Resolved import errors in `src/pages/groups` by moving customized zod schema and type from `src/api/routes/transcript.ts` to `src/shared/Transcript.ts`
- Added exception on `src/trpc.ts`'s reference to `src/api/apiRouter.ts`, this should be the only case allowing file outside `src/api` importing files under `src/api`

Resolve import errors and update eslint import restriction rules

---

.eslintrc.json

added Eslint rule `import/no-absolute-path` to forbid using absolute import paths

add no-absolute-path rule

---

package.json

a `prepare` script is added in `package.json` to automatically runs 'syncDatabase.ts' if the app is deploying on Vercel

Add 'prepare' script to auto-sync db while deploying

---

.env.template
next.config.js
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts

updated `next.config.js`
`environment` is adaptively changed to either "production" or "development"
`project` name is now changed to "app"
`SENTRY_AUTH_TOKEN` in `.env` is removed
`hideSourceMaps` is now `false`, sentry issues should show where the error happened in the source code. Further tests needed 
`ignoreErrors` is added to ignore any issues/errors from "localhost“
passed on developing both on local and Vercel

Update Sentry config and environment variables

---

src/pages/api/auth/[...nextauth].ts

NextAuth.js `createUser` [Event ](https://next-auth.js.org/configuration/events)is used to monitor if the user is new and created by the adapter.
**Note:** There are a couple of alternative ways to achieve this function like using a `signIn` event. However, using `jwt callback` does not work, suspecting the reason being that we used an adapter that will change the `session` default `strategy` to be "database" instead of "jwt", see [details](https://next-auth.js.org/configuration/options#session)

Add event to notify admin when new users registered

---

src/theme/buttons.ts

The `_hover` property was disabled if a `isDisabled` property was passed to the Button. 
The same color theme is passed to` _disabled` inside `_hover` and it should work now
[Login](https://drive.google.com/file/d/1nAiTxSu62tssKwh6HX6McUUcUvga_8bz/view) 
[User Management](https://drive.google.com/file/d/1qcEREXHBEAB4xxG0O4Imopck0SdTH7e4/view)

Fix button hovering style

---

src/api/auth.ts
src/components/AppPageContainer.tsx
src/pages/_app.tsx
src/pages/api/auth/[...nextauth].ts

- User data is included in the next-auth session and should be available by calling `useSession` instead of a `trpc.user.me query`.
- Type of `session.user` is declared as the `User` model.
- The website functions as normal including user login and new user signup.
- TODO: optimize redundant APIs and db calls with session data, such as removing trpc.user.me.query, and other unnecessary codes. Also check TODOs in auth.ts

Extend next-auth session data to include user fields

---

src/api/database/db.ts
src/api/database/models/TranscriptNameMapping.ts

The name mapping model is associated with transcript IDs so it is unique per transcript and could apply to all the summaries under the associated transcript. Group IDs are not used since the group members could change.

Create name mapping model

---

src/api/routes/summaries.ts
src/api/routes/transcripts.ts

- A try-catch block is added to the `summaries.list` to return the original summary text if handlebars.js is having errors compiling.
- The regex method to find handlebars are replaced with a stack method

Fix handlebar corner case 

---

src/api/database/db.ts
src/api/database/models/TranscriptNameMap.ts
src/api/routes/summaries.ts
src/api/routes/transcripts.ts
src/shared/Summary.ts
src/shared/Transcript.ts

- The APIs and functions named using `NameMap` are changed to `UserMap` for a more accurate description. 
- UserMap consists of a `zSummaryNameMap` type of `{ [handlebar]:  string, [userId]: string, [user]: MinUser }` which will be passed and used at the frontend. 
- `NameMap` is retained for its utility with summary.list. This ensures compatibility with handlebar.js when rendering summary texts.

modify handlebar backend api

---

package.json
yarn.lock

- This PR is to bump SendGrid/mail to resolve the [Depenabot alert](https://github.com/yuanjian-org/app/security/dependabot/17) of Axios Cross-site Request Vulnerability.
- Tests have been conducted and no issues were found when running in local or Vercel environments, should be ready to merge. 
- Dependabot should be able to create a security update for Axios after merging this PR.

Bump @sendgird/mail to 8.1.0

---

src/components/ChatRoom.tsx
src/components/MarkdownStyler.tsx
src/components/Transcripts.tsx
src/theme/MarkdownStyler.module.css

The Chakra UI CSSReset component would override the default styles of elements provided by the browsers, which could cause markdown texts not to display correctly as shown below.
A markdown styler component has been added with customized component styles to resolve this problem.

Add markdown styler to correctly render Markdown texts using Chakra UI

---

src/components/MarkdownStyler.tsx

[issue 272](https://github.com/yuanjian-org/app/issues/272) reported that strikethrough is not recognized correctly. 
According to react-markdown official, the original dependency does not support strikethrough, so the plugin [remark-gfm](https://github.com/remarkjs/remark-gfm) is added and used as [shown in the README.](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use)
Now strikethrough is working properly as shown below

Comment on remark-gfm to support GitHub Flavored Markdown(GFM)

---

src/pages/auth/login.tsx

This issue is related to [issue 92](https://github.com/yuanjian-org/app/issues/92)
Currently, if we are disconnected from database and the user tries to log in, the toast is not displayed properly when the backend server returns error code 500.
Now, the toast error message is displayed as intended.

fix: fix toast error fails to show during network disconnection on login

---

src/api/routes/groups.ts
src/pages/groups.tsx

This pr is related to [issue 241](https://github.com/yuanjian-org/app/issues/241)
Currently, the system enforces that each group must have two or more members:
The create group button (创建自由分组) is disabled if there is only one user entered:
The single-member group edit window shows an error message: "需要至少两名用户" (At least two users are required):
Now, the system allows single-member groups:

feat: allow single-member groups

---

src/api/TencentMeeting.ts
src/api/routes/summaries.ts
src/shared/Summary.ts

- A new Tencent Meeting API has been integrated to fetch speaker names and speech times per meeting. Two utility functions were added to decode usernames from Base64 and convert speech times from milliseconds to minutes.
- In `summaries.ts`, the `summaryKey` property of `SummaryDescriptor` has been updated to `summaryDetails`, which now includes both summary keywords and speaker details.
- In `findMissingCrudeSummariesforTmUser`, the function will now fetch and store speaker information after confirming the availability of AI minutes for the specific transcript summaries.

Fix #280: download speaker duration summary from tencentmeeting and display it on transcript UI

---

src/components/ChatRoom.tsx

Fixed #295 
If the note has been updated, both the creation date and the last modification date will be shown. 
If the note has not been updated, only the creation date will be displayed
Previous:
After change:

Added creation date in chatroom note

---

src/components/AutosaveIndicator.tsx
src/components/MobileExperienceAlert.tsx
src/components/Navbars.tsx
src/pages/interviews/[interviewId].tsx

In the old UI, the auto-save indicator is at the top-right without margin. 
After the change, the indicator is at the top-right with margin:
Adjust the thickness of outline, no much difference since the background is largely white:

Move auto-save indicator to the center and stick at the top

---

src/pages/mentees.tsx

Fixed https://github.com/yuanjian-org/app/issues/327.
1. Re-rendering Issue: Each time the menteeCell component re-renders, it triggers a tRPC query which can be found here: [trpc query](https://github.com/yuanjian-org/app/compare/sort_table_function?expand=1#diff-065d898ce719572a882d2db4ba49094c4557609c70696bdd082c874845e3056fR170).
2. State Management: Additional React lifecycle hooks are being maintained: useState and useEffect, which are located here: [useState](https://github.com/yuanjian-org/app/compare/sort_table_function?expand=1#diff-065d898ce719572a882d2db4ba49094c4557609c70696bdd082c874845e3056fR81) and [useEffect](https://github.com/yuanjian-org/app/compare/sort_table_function?expand=1#diff-065d898ce719572a882d2db4ba49094c4557609c70696bdd082c874845e3056fR175).
3. Efficiency of …

Sort user using call back function

---

src/api/database/models/map/LandmarkScoreLog.ts

Remove `@ primary key` from `userId` and `landmark` fields of the Map model

Remove primary key tags from map model

---

src/api/database/models/User.ts
src/api/database/models/map/LandmarkAssessment.ts

Add `assessorId` in `LandmarkAssessment`to allow permitted users to access specific Landmark assessment histories.

Add AssessorId to LandmarkAssessment Table

---

src/pages/coachees.tsx

Fixed #402 by adding a source column

add source column

---

src/components/Sidebar.tsx

Fixed #392.
If current window size is smaller, able to scroll down the side bar.

make sidebar dragable to see user menu

---

src/components/MarkdownStyler.tsx
src/theme/MarkdownStyler.module.css

Chat container

---

src/components/GroupBar.tsx

fixed #369 
When the button is clicked, it should always attempt to open in a new window. If the pop-up window is blocked, then it should open in the current window.

try open in new window otherwise open in current window

---

src/api/routes/users.ts
src/components/Applicant.tsx

After a user or a user manager update the wechat field value to empty, the invariant is checking not null and causing error in both 面试页 and申请页.
https://github.com/yuanjian-org/app/blob/52347819e494142fce24e165cc9f1aa810d4e195/src/components/Applicant.tsx#L109

set default wechat value if null
